import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

function git(cmd) {
  try {
    return execSync(cmd, { encoding: "utf8" }).trim();
  } catch {
    return null;
  }
}

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const version = pkg.version || "0.0.0";

const commitFull =
  git("git rev-parse HEAD") ||
  process.env.COMMIT_REF ||
  process.env.NETLIFY_COMMIT_REF ||
  "unknown";
const commit =
  git("git rev-parse --short HEAD") ||
  (commitFull !== "unknown" ? commitFull.slice(0, 7) : "unknown");
const message =
  git('git log -1 --pretty=%s') ||
  process.env.COMMIT_MESSAGE ||
  process.env.NETLIFY_COMMIT_MESSAGE ||
  "No commit message";
const author =
  git('git log -1 --pretty=%an') ||
  process.env.COMMIT_AUTHOR ||
  "unknown";
const builtAt = new Date().toISOString();

const info = { version, commit, commitFull, message, author, builtAt };

const txt = `Daybook Life OS
Version: ${version}
Commit: ${commit} (${commitFull})
Message: ${message}
Author: ${author}
Built: ${builtAt}
`;

writeFileSync("public/versioninfo.txt", txt);

mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/version.js",
  `// Auto-generated by scripts/generate-version.mjs — do not edit\nexport const VERSION_INFO = ${JSON.stringify(info, null, 2)};\n`
);

console.log(`versioninfo.txt → v${version} @ ${commit}`);
